name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: Breaking Changes
    labels:
      - breaking-change
      - BC
  - title: Features
    labels:
      - enhancement
      - feature
  - title: Bug Fixes
    labels:
      - bug
      - fix
  - title: Maintenance
    labels:
      - chore
      - dependencies
      - refactor
      - tests
  - title: Documentation
    labels:
      - docs
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '"`' # escape double quotes and backticks
exclude-labels:
  - skip-changelog
template: |
  ## What's Changed

  $CHANGES

  --
  Compare: $COMPARE_URL
